SELECT TOP (1000) [Turbine]
      ,[Time]
      ,[Production]
      ,[PowerMin]
      ,[PowerMax]
      ,[PowerAvg]
      ,[Energy]
      ,[WindDirection]
      ,[WindSpeed]
  FROM [WindDB_Trinity].[dbo].[MeasurementSet3]